application: mywebfont
version: 1
runtime: python
api_version: 1

handlers:
- url: /font/.*
  script: font.py

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js
  
- url: .*
  script: main.py
